### ISSUE TITLE
[PE-D][Tester E] Email validation Regex

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W11-1/tp#213]
john@example.com.com.com.com.com is accepted as a valid email regex but it is not a valid email

![Screenshot 2024-04-05 at 4.14.53 PM.png](https://raw.githubusercontent.com/tanjiajiajun/ped/main/files/710f726d-8b07-455b-ba27-cd6a6f465698.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tanjiajiajun/ped#2

**Comment by LWS49** [comment]
Functionality bug. Update the REGEX for email. Strictly incorrect.

**Comment by jieqiboh** [comment]
According to the MESSAGE_CONSTRAINTS and UG, having multiple domain labels separated by multiple periods is the advertised behaviour, so this isn't incorrect?
