### ISSUE TITLE
[PE-D][Tester B] Input for setdeadline accepts invalid dates

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W11-1/tp#218]
Reproduce from sample data by executing the commands:
1. addtask 1 /task callback
2. setdeadline 1 /selecttask 1 /deadline 31/04/2024

This updates the deadline to 31/04/2024 which is not a valid date, as there are only 30 days in April. Do consider other bugs like this that can be found through boundary value analysis.

![image.png](https://raw.githubusercontent.com/biinnnggggg/ped/main/files/122ffca7-a0ce-4011-a15d-705aa9388927.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: biinnnggggg/ped#2

**Comment by LWS49** [comment]
Documentation bug. Specify in known issues in UG that deadline accepts invalid dates as long as the day, month and year are individually valid (like 31/02/2022 will be accepted, even though it's not a valid date).
Specify in message constraints, field summary in UG.
