### ISSUE TITLE
[PE-D][Tester E] Remark field can be empty string

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W11-1/tp#231]
eg edit 1 /remark is accepted

![Screenshot 2024-04-05 at 4.52.59 PM.png](https://raw.githubusercontent.com/tanjiajiajun/ped/main/files/05541785-c2d4-4320-9e59-0a886f5f7784.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: tanjiajiajun/ped#9

**Comment by LWS49** [comment]
Documentation bug. UG tips for edit add that /remark can be blank (transfer from /addremark to top)
Check field restriction for edit  command in UG.
