### ISSUE TITLE
[PE-D][Tester B] find command /status field accepting invalid input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W11-1/tp#236]
Current:

![image.png](https://raw.githubusercontent.com/biinnnggggg/ped/main/files/5f249f83-22d7-46d2-afce-354d339e59b5.png)

Input: `find withany /status invalid_status`
Output:
![image.png](https://raw.githubusercontent.com/biinnnggggg/ped/main/files/afdc6c61-feda-41cc-be86-f571de441334.png)

Intended output should be that an error message saying that its an invalid input. This is an issue.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: biinnnggggg/ped#7

**Comment by LWS49** [comment]
Planned enhancement. Specify that find function will have checks in the future.
