### ISSUE TITLE
Update the UG

### ISSUE THREAD

**Issue by theman-oj10** [AY2324S2-CS2103T-W11-1/tp#36]
Update the current UG to include new features and cater to CS students applying for internships.

**Comment by theman-oj10** [comment]
Jie Qi: entry fields
Wei Sheng: update command
Hari: add & delete command
Manoj: sample data
Donovan: interface

**Comment by CaptainKeqing** [comment]
Missing:

1) Jie Qi
2) Manoj
3) Wei Sheng
